nvd:
    api_key: 39600df5-47e6-4fd9-a468-a3d5c309e3b1
    cpe_url: https://services.nvd.nist.gov/rest/json/cpes/2.0
    cve_url: https://services.nvd.nist.gov/rest/json/cves/2.0
server:
    web_port: "8080"
ui:
    theme: theme-pink
database:
    main_db_path: ./internal/data/sql-data.db
    cpe_db_path: ./internal/data/cpe.db
