// models.go contains the data models/structs that are used jointly between agents and server

package shared

import (
	"encoding/json"
	"time"
)

// Software defines the data associated with a given software installation.
type Software struct {
	Name         string `json:"name"`
	Version      string `json:"version"`
	Manufacturer string `json:"manufacturer"`
	Date         string `json:"date"`
}

// Envelope is the common wrapper for all data uploads.
type Envelope struct {
	AgentID   string          `json:"agent_id"`
	Timestamp time.Time       `json:"timestamp"`
	Payload   json.RawMessage `json:"payload"`
}

// RegistrationRequest is what the agent sends during helloPacket/enrollment
type RegistrationRequest struct {
	MachineID     string `json:"machine_id"`
	Hostname      string `json:"hostname"`
	OS            string `json:"os"`
	OSVersion     string `json:"os_version"`
	BinaryVersion string `json:"binary_version"`
	Token         string `json:"token"`
}

type Agent struct {
	// Unique Identifiers
	AgentID   string `json:"agent_id"` // UUID generated by server during enrollment
	Hostname  string `json:"hostname"`
	MachineID string `json:"machine_id"` // Unique HW ID (from registry or /etc/machine-id)

	// System Information
	OS        string `json:"os"`
	OSVersion string `json:"os_version"`
	LocalIP   string `json:"local_ip"`

	// Status Tracking
	Status    string    `json:"status"`        // "online", "offline"
	FirstSeen time.Time `json:"first_seen"`    // Enrollment timestamp
	LastSeen  time.Time `json:"last_seen"`     // Last heartbeat/telemetry timestamp
	Version   string    `json:"agent_version"` // Version of agent binary (e.g., "1.0.2")
}

// Data received from the agent to the server in a heartbeat
type HeartbeatData struct {
	AgentID  string `json:"agent_id"`
	Hostname string `json:"hostname"`
}

// Data sent from server to agent in a heartbeat response
type HeartbeatResponse struct {
	Status             string `json:"status"`
	TelemetryFrequency int    `json:"telemetry_freq"`
}
